# Generated by Django 3.2.3 on 2022-02-12 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0002_gruposatendimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Digite o nome da vacina.', max_length=200)),
                ('fabricante', models.CharField(help_text='Digite o nome do fabricante da vacina.', max_length=200)),
            ],
            options={
                'verbose_name': 'Vacina',
                'verbose_name_plural': 'Vacinas',
                'ordering': ['nome', 'fabricante'],
            },
        ),
    ]
