# Generated by Django 3.2.3 on 2022-02-12 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0003_vacina'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalVacinacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Digite o nome do local.', max_length=200)),
                ('logradouro', models.CharField(help_text='Digite o logradouro.', max_length=200)),
                ('bairro', models.CharField(help_text='Digite o bairro.', max_length=200)),
                ('cidade', models.CharField(help_text='Digite a cidade.', max_length=200)),
                ('cnes', models.CharField(help_text='Digite o CNES.', max_length=200, verbose_name='CNES')),
            ],
            options={
                'verbose_name': 'Local de Vacinação',
                'verbose_name_plural': 'Locais de Vacinação',
                'ordering': ['cidade', 'bairro', 'logradouro', 'nome'],
            },
        ),
    ]
